
---
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: custom-networking
spec:
  role: eks-auto-module-demo-eks-auto-20260111195816023800000003
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-auto-module-demo
  securityGroupSelectorTerms:
    - id: sg-01717bba704641be3
  tags:
    Project: EKS-Auto-Learning
    Owner: Dilip
    CostCenter: Learning-02

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cost-optimized
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: custom-networking
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]
